const geometry = require("./geometry");
const utilities = require("./utilities");

console.log("Test Geometry");
console.log("Volume of Rectangular Prism");
console.log(geometry.volumeOfRectangularPrism(5,4,1));
console.log(geometry.volumeOfRectangularPrism(5,9,2));
//console.log(geometry.volumeOfRectangularPrism(5,4,0));
//console.log(geometry.volumeOfRectangularPrism(5,"",4));
//console.log(geometry.volumeOfRectangularPrism(5,"a",1));
console.log("Surface Area of Rectangular Prism");
console.log(geometry.surfaceAreaOfRectangularPrism(5,4,1));
console.log(geometry.surfaceAreaOfRectangularPrism(5,9,2));
console.log("Volume of Sphere");
console.log(geometry.volumeOfSphere(5));
//console.log(geometry.volumeOfSphere());
console.log("Surface Area of Sphere");
console.log(geometry.surfaceAreaOfSphere(5));
console.log("-------------------------------");
console.log("Test Utilities");
console.log("Deep Equality");
const first = {a:1, b:2, c:3};
const second = {a:2, b:2, c:3};
const third = {a:1, b:2, c:3};
console.log(utilities.deepEquality(first, second));
console.log(utilities.deepEquality(first, third));
//console.log(utilities.deepEquality(first, ));
console.log("Unique Elements");
const testArr = ["a", "a", "b", "a", "b", "c"];
console.log(utilities.uniqueElements(testArr));
console.log("Count of Each Character in String");
const test = "Hello, the pie is in the oven";
const charMap = utilities.countOfEachCharacterInString(test);
console.log(charMap);